VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "VBAParseItem"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
' VBAParseItem Type Declaration

Public lngLine As Long
Public strTicker As String
Public strDate As String
Public dblOpen As Double
Public dblHigh As Double
Public dblLow As Double
Public dblClose As Double
Public lngVol As Long
